project:
  type: website
  output-dir: docs

website:
  title: "NewYear"
  site-url: "https://harveyl888.github.io/newyear/"

format:
  html:
    theme: cosmo
    css: styles.css
    embed-resources: true



